#!/bin/sh
#
# test running programs on simulated time

INTERVAL=1
RUNTIME=30

for I in 1 2 3 4;
do
	timeexec example &
done

# sleep 1
# timerun $RUNTIME
# exit

sleep $INTERVAL
timerun $RUNTIME
sleep $INTERVAL
timerun $RUNTIME
sleep $INTERVAL
timerun $RUNTIME
sleep $INTERVAL
timerun $RUNTIME

wait

